version: '3'

services:
  db:
    image: postgres:10
    container_name: db
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - volume-db:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    hostname: db
    restart: always
  app:
    build:
      context: ../
      dockerfile: ./docker/app/Dockerfile
    env_file: .env
    ports:
      - 80:4000
volumes:
  volume-db:
    driver: local